name: Run crank

on:
  push:
    branches:
      - main

jobs:
  run-crank:
    name: Run crank
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: npm
          corepack-enable: true

      - name: Install Dependencies
        id: yarn-ci
        run: yarn install

      - name: Run bot
        id: run-bot
        run: yarn start
